/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.leo.serialize.avro.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PhoneType { 
  MOBILE, HOME, WORK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PhoneType\",\"namespace\":\"org.leo.serialize.avro.domain\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
