/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.leo.serialize.avro.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PhoneNumber extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PhoneNumber\",\"namespace\":\"org.leo.serialize.avro.domain\",\"fields\":[{\"name\":\"number\",\"type\":\"string\"},{\"name\":\"type\",\"type\":{\"type\":\"enum\",\"name\":\"PhoneType\",\"symbols\":[\"MOBILE\",\"HOME\",\"WORK\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence number;
  @Deprecated public org.leo.serialize.avro.domain.PhoneType type;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use {@link \#newBuilder()}. 
   */
  public PhoneNumber() {}

  /**
   * All-args constructor.
   */
  public PhoneNumber(java.lang.CharSequence number, org.leo.serialize.avro.domain.PhoneType type) {
    this.number = number;
    this.type = type;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return number;
    case 1: return type;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: number = (java.lang.CharSequence)value$; break;
    case 1: type = (org.leo.serialize.avro.domain.PhoneType)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'number' field.
   */
  public java.lang.CharSequence getNumber() {
    return number;
  }

  /**
   * Sets the value of the 'number' field.
   * @param value the value to set.
   */
  public void setNumber(java.lang.CharSequence value) {
    this.number = value;
  }

  /**
   * Gets the value of the 'type' field.
   */
  public org.leo.serialize.avro.domain.PhoneType getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(org.leo.serialize.avro.domain.PhoneType value) {
    this.type = value;
  }

  /** Creates a new PhoneNumber RecordBuilder */
  public static org.leo.serialize.avro.domain.PhoneNumber.Builder newBuilder() {
    return new org.leo.serialize.avro.domain.PhoneNumber.Builder();
  }
  
  /** Creates a new PhoneNumber RecordBuilder by copying an existing Builder */
  public static org.leo.serialize.avro.domain.PhoneNumber.Builder newBuilder(org.leo.serialize.avro.domain.PhoneNumber.Builder other) {
    return new org.leo.serialize.avro.domain.PhoneNumber.Builder(other);
  }
  
  /** Creates a new PhoneNumber RecordBuilder by copying an existing PhoneNumber instance */
  public static org.leo.serialize.avro.domain.PhoneNumber.Builder newBuilder(org.leo.serialize.avro.domain.PhoneNumber other) {
    return new org.leo.serialize.avro.domain.PhoneNumber.Builder(other);
  }
  
  /**
   * RecordBuilder for PhoneNumber instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PhoneNumber>
    implements org.apache.avro.data.RecordBuilder<PhoneNumber> {

    private java.lang.CharSequence number;
    private org.leo.serialize.avro.domain.PhoneType type;

    /** Creates a new Builder */
    private Builder() {
      super(org.leo.serialize.avro.domain.PhoneNumber.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.leo.serialize.avro.domain.PhoneNumber.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
    }
    
    /** Creates a Builder by copying an existing PhoneNumber instance */
    private Builder(org.leo.serialize.avro.domain.PhoneNumber other) {
            super(org.leo.serialize.avro.domain.PhoneNumber.SCHEMA$);
      if (isValidValue(fields()[0], other.number)) {
        this.number = data().deepCopy(fields()[0].schema(), other.number);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
    }

    /** Gets the value of the 'number' field */
    public java.lang.CharSequence getNumber() {
      return number;
    }
    
    /** Sets the value of the 'number' field */
    public org.leo.serialize.avro.domain.PhoneNumber.Builder setNumber(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.number = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'number' field has been set */
    public boolean hasNumber() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'number' field */
    public org.leo.serialize.avro.domain.PhoneNumber.Builder clearNumber() {
      number = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'type' field */
    public org.leo.serialize.avro.domain.PhoneType getType() {
      return type;
    }
    
    /** Sets the value of the 'type' field */
    public org.leo.serialize.avro.domain.PhoneNumber.Builder setType(org.leo.serialize.avro.domain.PhoneType value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'type' field has been set */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'type' field */
    public org.leo.serialize.avro.domain.PhoneNumber.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public PhoneNumber build() {
      try {
        PhoneNumber record = new PhoneNumber();
        record.number = fieldSetFlags()[0] ? this.number : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (org.leo.serialize.avro.domain.PhoneType) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
